import ChatWindow from "@/components/layout/chat-window";
import SideBar from "@/components/layout/sidebar";
import { activeUserAtom } from "@/recoil/atoms/active-user/active-user-atom";
import { Box, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useRecoilValue } from "recoil";

export default function Home() {
  const activeUser = useRecoilValue(activeUserAtom);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box minHeight={"100vh"} bg="app-bg" position={"relative"}>
          <SideBar />
          {activeUser && <ChatWindow />}
        </Box>
      </main>
    </>
  );
}
